language: node_js
node_js:
- stable
before_script:
- npm install
script: bash ./deploy.sh
env:
  global:
    secure: F8s5+9YSPDEvfxIfy5NaWncDTth99+4HvghNDNU9rCvF+Pw6F8CJJ/eOIEuek9JsI80Gp0KJNFlsznkrcsFygHuAaPq9Ky5BQePMcJAL3YRO2kwhIIwSp7RXDV4IRx5fA6pSM0lT3ldO7WtotHRTblePtUPC7i+hE0Lb/1BbMeI41J3CLcZR1gI3gd6J7Rd/ABs6J6g8Zkuws3//WR0Pm4xi8QXTwuOT43UyMvToyCETAsXi8gHer/wtY6ZxUFhN75gEwi0Cbt8TEyvLkKUtDxfDleuCbWh7BG3Ysthm0OJg2EGyMWmQWI4mUNU5Gi05CTYOlu9O3J+gCYzXnT0LIhjMCNms6HUC0GL/VCLZXbV287XXvbMboUiGsr1AnaNzAZ+bwXS6+EQw5qDWHx9hSK8/fCoK+o19UDV+5numZDQSkzIJ748eXIUNps16v6idrQGndF5tZKboppuo88OOKrh58g5Xmz1JdP1gCLERCs1JzMFgXHg9ZEyxtuxMV1EwQ8k3sUnf/I6WaoL4ATUZt5f+sGtRo0D5LaKyYXH3TMBCl8l3Nm7yBDbLHApfuaOODvu2zLJiPddx8agWnHQzlGpwlCoS2arQIF79tdteaML9LG9QihgnHMBUzuwm54SVBO9z7j+40hyq1h8wFFtzPk3GxI0y0zkYrGRvOftGOkY=
