#%RAML 1.0
title: New API
types:
  productorder:
    description: 'Por meio dessa API é possível inserir, atualizar e consultar as informações dos pedidos de produto'
    type: object
    properties:
      ID:
        required: false
        example: Example
        description: Property description
        type: string
      timestamp:
        required: false
        example: '2018-03-23T12:07:11.000Z'
        format: rfc3339
        description: Property description
        type: datetime
      dealerNumber:
        required: true
        example: 1
        description: Property description
        type: integer
      orderNumber:
        required: true
        example: AOL-99999
        description: Property description
        type: string
      erpOrderNumber:
        required: false
        example: Example
        description: Property description
        type: string
      status:
        required: true
        example: Example
        description: Property description
        type: string
  error412:
    description: This is a new DataType
    type: object
    properties:
      errorCode:
        required: true
        example: Example
        description: Property description
        type: string
      message:
        required: true
        example: Example
        description: Property description
        type: string
/new-resource:
  post:
    responses:
      '200':
        body:
          application/json:
            type: object
            properties:
              productOrder:
                required: true
                description: Property description
                type: productorder
      '412':
        body:
          application/json:
            type: object
            properties:
              error:
                required: true
                description: Property description
                type: error412
    headers:
      Authorization:
        example: Bearer <Token>
        description: Property description
        type: string
      Content-Type:
        example: Example
        description: Property description
        default: application/json
        type: string
    body:
      application/json:
        type: object
        properties:
          productOrder:
            required: true
            description: Property description
            type: productorder
  get:
    responses:
      '200':
        body:
          application/json:
            type: object
            properties:
              productOrder:
                required: true
                description: Property description
                type: productorder
      '201': {}
    queryParameters:
      dealerNumber:
        example: 1
        description: Property description
        type: integer




